---
- name: Create Directory /etc/avahi/services/
  become: true
  ansible.builtin.file:
    owner: root
    group: root
    mode: '0755'
    state: directory
    path: "{{ item }}"
  with_items:
    - '/etc/avahi'
    - '/etc/avahi/services'
  notify:
    - Run systemctl restart avahi-daemon.service

- name: Copy configured avahi services
  become: true
  ansible.builtin.template:
    src: 'templates/avahi.service.j2'
    dest: "/etc/avahi/services/{{ item.service | lower }}.service"
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  notify:
    - Run systemctl restart avahi-daemon.service
  with_items: "{{ avahi_daemon__services }}"
