---
- name: Update apt cache
  become: true
  ansible.builtin.apt:
    cache_valid_time: 3600
    update_cache: true
  when:
    - ansible_pkg_mgr == "apt"

- name: Install avahi packages
  become: true
  ansible.builtin.package:
    name: "{{ avahi_daemon__packages }}"
    state: present
  notify:
    - Run systemctl restart avahi-daemon.service
