---
- name: Run optional versionscheck
  ansible.builtin.include_tasks:
    file: versioncheck.yml
  when: submodules_versioncheck | bool

- name: Gather os specific variables
  ansible.builtin.include_vars:
    file: "{{ item }}"
  with_first_found:
    - "vars/{{ ansible_os_family }}.yml"
    - "vars/os_fallback.yml"

- name: Install avahi requirements
  ansible.builtin.include_tasks:
    file: install.yml

- name: Optionally announce avahi services
  ansible.builtin.include_tasks:
    file: avahi_services.yml
