---
- name: Make sure avahi-daemon.service is started
  ansible.builtin.systemd_service:
    name: 'avahi-daemon.service'
    state: 'started'
    enabled: 'true'
  become: true
  notify:
    - Run systemctl restart avahi-daemon.service
